version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4200:4200"
    env_file:
      - ./backend/.env
    # depends_on:
    #   - mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.local`)"
      - "traefik.http.services.backend.loadbalancer.server.port=4200"
    networks:
      - bridge_networks_1

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.local`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - bridge_networks_1

  mysql:
    image: mysql:8.0
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    networks:
      - bridge_networks_1
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql-exporter:
    image: prom/mysqld-exporter
    env_file:
      - ./backend/.env
    environment:
      DATA_SOURCE_NAME: "root:${MYSQLDB_ROOT_PASSWORD}@(mysql:${MYSQLDB_LOCAL_PORT})/"
    ports:
      - "9104:9104"
    networks:
      - bridge_networks_1

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - bridge_networks_1

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - bridge_networks_1

  backup:
    build: ./backup
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backups:/backup
    depends_on:
      - mysql
    networks:
      - bridge_networks_1

  traefik:
    image: traefik:v2.5
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
    networks:
      - bridge_networks_1

volumes:
  mysql-data:
  grafana-data:

networks:
  bridge_networks_1:
